version: "3.8"

services:
  db1:
    image: postgres:17.5-bookworm
    container_name: postgres-db1
    restart: unless-stopped
    environment:
      POSTGRES_USER: ego
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: database_test1
    ports:
      - "5433:5432"
    volumes:
      - pgdata1:/var/lib/postgresql/data
    networks:
      - postgres-network

  db2:
    image: postgres:17.5-bookworm
    container_name: postgres-db2
    restart: unless-stopped
    environment:
      POSTGRES_USER: ego
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: database_test2
    ports:
      - "5434:5432"
    volumes:
      - pgdata2:/var/lib/postgresql/data
    networks:
      - postgres-network

  db3:
    image: postgres:17.5-bookworm
    container_name: postgres-db3
    restart: unless-stopped
    environment:
      POSTGRES_USER: ego
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: database_test3
    ports:
      - "5435:5432"
    volumes:
      - pgdata3:/var/lib/postgresql/data
    networks:
      - postgres-network

volumes:
  pgdata1:
  pgdata2:
  pgdata3:

networks:
  postgres-network:
    driver: bridge
